### ISSUE TITLE
[FE][Feature] RetroList API 연결

### ISSUE THREAD

**Issue by yeneua** [donga-it-club/past-forward-frontend#93]
## 어떤 기능인가요?

RetroList API 연결

## 작업 상세 내용

- [ ] API 연결 이해하기
- [ ] API 연결

**Comment by yeneua** [comment]
pull 받다가 브랜치가 너무 꼬여버려서 해당 브랜치 삭제하고 새 브랜치로 작업하겠습니다 ...

**Comment by jeongmin59** [comment]
예나님! 해당 브랜치 삭제 부탁드릴게요~!
